name: Run My Script Every 12 Hours

# When to run the workflow
on:
  workflow_dispatch:    # allows manual run
  schedule:
    - cron: '0 */12 * * *'  # runs every 12 hours

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      MY_API_KEY: ${{ secrets.MY_API_KEY }}  # your API key from GitHub Secrets
    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4

      # Step 2: Set up Python (choose your version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies if needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      # Step 4: Run your script
      - name: Run script
        run: python update_rates.py
