name: Run script

on:
  workflow_dispatch:    # allows manual run
  schedule:
    - cron: '0 */12 * * *'  # runs every 12 hours

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      MY_API_KEY: ${{ secrets.MY_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: python update_rates.py
